### ISSUE TITLE
Riak-mesos cluster create fails after reinstallation of framework

### ISSUE THREAD

**Issue by ChiralMedia** [basho-labs/riak-mesos-tools#17]
Mesos 0.28.1   DC/OS 1.7  Riak framework 0.1.1

Riak-mesos cluster create fails after reinstallation of framework.

Cluster is not created, Zookeeper lists Riak, but no cluster is listed, subsequent calls to riak-mesos cluster list also results in large amount of output that looks like config, but no clusters are listed. DC/OS cli of “dcos riak cluster list” returns no clusters.

Adding nodes also fails, file is attached for reference.

[ClusterCreate.txt](https://github.com/basho-labs/riak-mesos-tools/files/363743/ClusterCreate.txt)
[ClusterList_After_ClusterCreate.txt](https://github.com/basho-labs/riak-mesos-tools/files/363744/ClusterList_After_ClusterCreate.txt)
[AttemptsToCreateNodesAfterClusterCreation.txt](https://github.com/basho-labs/riak-mesos-tools/files/363752/AttemptsToCreateNodesAfterClusterCreation.txt)

**Comment by sanmiguel** [comment]
As per #24, this is a problem with using the older framework version, fixed by upgrading to 1.0.0+

If that's not the case, please feel free to re-open this issue.
