### ISSUE TITLE
Install of v1.0.0 fails

### ISSUE THREAD

**Issue by ChiralMedia** [basho-labs/riak-mesos-tools#24]
Install fail with the following:

[u1@bootstrapper ~]$ dcos package search riak
NAME VERSION SELECTED FRAMEWORK DESCRIPTION
riak 1.0.0 False True A distributed NoSQL key-value data store that offers high availability, fault...
[u1@bootstrapper ~]$
[u1@bootstrapper ~]$ dcos package install --options=/etc/riak-mesos/config.json riak
The Riak framework should have at least 1GB of RAM and 0.5 CPUs to perform successfully.
Continue installing? [yes/no] yes
Package file [marathon.json] is not JSON: expected json value got h (line 24, column 1620)
[u1@bootstrapper ~]$

**Comment by sanmiguel** [comment]
Today we have released [v1.2.1](https://github.com/basho-labs/riak-mesos-scheduler/releases/1.2.1) of the Scheduler, which includes fixes for this very problem. You will need to reinstall the dcos package repo, from https://github.com/basho-labs/riak-mesos-dcos-repo/archive/master.zip and make a couple of small changes to `/etc/riak-mesos/config.json`: 
 - change `.riak.scheduler.url` and `.riak.scheduler.package` to use v1.2.1 linked above
 - change the value at `.riak.scheduler.constraints` to be a quoted JSON string, e.g. 

``` json
 "constraints": "[[ \"hostname\", \"UNIQUE\" ]]"
```

Please let us know if this does not address the problem.

**Comment by ChiralMedia** [comment]
Install now completes thanks.
