### ISSUE TITLE
Environment settings ignore configuration file

### ISSUE THREAD

**Issue by ChiralMedia** [basho-labs/riak-mesos-tools#25]
When installed most environment shown are for Ubuntu rather than Centos7 as configured (config.json attached).

RIAK_MESOS_DIRECTOR_URL=https://github.com/basho-labs/riak-mesos-director/releases/download/1.0.1/riak_mesos_director-1.0.1-centos-7.tar.gz
RIAK_MESOS_EXECUTOR_PKG=riak_mesos_executor-1.2.0-mesos-0.28.1-ubuntu-14.04.tar.gz
RIAK_MESOS_EXPLORER_PKG=riak_explorer-1.1.1.patch-ubuntu-14.04.tar.gz
RIAK_MESOS_PATCHES_PKG=riak_erlpmd_patches-1.2.0-mesos-0.28.1-ubuntu-14.04.tar.gz
RIAK_MESOS_RIAK_PKG=riak-2.1.4-ubuntu-14.04.tar.gz
RIAK_MESOS_SCHEDULER_PKG=riak_mesos_scheduler-1.2.1-mesos-0.28.1-ubuntu-14.04.tar.gz

[config.json.txt](https://github.com/basho-labs/riak-mesos-tools/files/378301/config.json.txt)

**Comment by sanmiguel** [comment]
I think I see the problem, assuming you installed this with the exact command you pasted in issue #24 

The `--options foo.json` argument needs to go after the package name. Try with:

```
dcos package install riak --options=/etc/config/riak.json
```

Unfortunately `dcos` CLI doesn't tell you this and will quietly ignore your configuration file if you put `--options` before the package name.

I've added a change to our README to call this out more explicitly (https://github.com/basho-labs/riak-mesos-tools/pull/27)

**Comment by ChiralMedia** [comment]
Uninstalled package, removed /riak node from Zookeeper
Reinstalled with dcos package install riak --options=/etc/config/config.json
No change in the environment settings displayed, they're still Ubuntu.

**Comment by sanmiguel** [comment]
Ah, I see another problem: if you're installing under DCOS you will need to use the [https://github.com/basho-labs/riak-mesos-tools/blob/master/config/config.dcos.json](config.dcos.json) as a template, as there are some differences in the configuration from outside of DCOS.

For example, you need to have corresponding `"package"` values for each `"url"` value. You'll need to add these for all of the following:

 - `.riak.scheduler.url` -> `.riak.scheduler.package`
 - `.riak.executor.url` -> `.riak.executor.package`
 - `.riak.node.url` -> `.riak.node.package`
 - `.riak.node.patches-url` -> `.riak.node.patches-package`
 - `.riak.node.explorer-url` -> `.riak.node.explorer-package`
 - `.riak.director.url` -> `.riak.director.package`

**Comment by ChiralMedia** [comment]
Thanks for that, the config file change has fixed the env settings.




________________________________

**Comment by sanmiguel** [comment]
Excellent, glad that helped.
