### ISSUE TITLE
director uninstall does not include framework name in marathon app-name prefix

### ISSUE THREAD

**Issue by mokele** [basho-labs/riak-mesos-tools#46]
install uses `director_marathon_name = "-".join((framework, cluster, 'director'))`
yet uninstall uses `/' + cluster + '-director' so it is not currently possible to remove the directory via riak-mesos-tools

**Comment by sanmiguel** [comment]
Hi! I just merged #50 (and tagged the tools at [1.3.1](https://github.com/basho-labs/riak-mesos-scheduler/releases/1.3.1) ) which addresses this.

I'll close the issue but please feel free to reopen if you continue to have this problem.
